<a href="https://colab.research.google.com/github/isacNepo/aulas_faculdade/blob/master/Aula_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vetores (NumPy)

NumPy é uma biblioteca muito poderosa, utilizada para efetuar cálculos matemáticos de forma fácil e transparente ao programador Python.

* shape - informa a quantidade de colunas de um vetor.
* dtype - indicará qual o tipo de dado dos valores armazenados no vetor.
* size - retorna a quantidade de elementos do vetor e/ou matriz.
* itemsize - retorna o tamanho de um elemento da matriz em bytes
* ndim - retornará o número de dimensões da matriz

## Criando vetores em NumPy

In [1]:
# Importar a biblioteca NumPy.
import numpy as np

In [2]:
# Exemplo de um vetor NumPy.

vetor = np.array([8, 34, 67, 98] )

In [3]:
# Imprimindo dados do vetor
print(vetor)
print("Shape:",vetor.shape)
print("Dtype:",vetor.dtype)
print("Size:",vetor.size)
print("Itemsize:",vetor.itemsize)
print("Ndim:", vetor.ndim)

[ 8 34 67 98]
Shape: (4,)
Dtype: int64
Size: 4
Itemsize: 8
Ndim: 1


### Outro exemplo

In [5]:
vetor = np.array([8.87, 34, 67.89, 98, 1.09])

In [6]:
print(vetor)
print("Shape:",vetor.shape)
print("Dtype:",vetor.dtype)
print("Size:",vetor.size)
print("Itemsize:",vetor.itemsize)
print("Ndim:", vetor.ndim)

[ 8.87 34.   67.89 98.    1.09]
Shape: (5,)
Dtype: float64
Size: 5
Itemsize: 8
Ndim: 1


## Acessando e alterando vetores

In [7]:
vetor = np.array([8, 34, 67, 98] )
print("Vetor posicao 0:",vetor[0]);
print("Vetor posicao 2:",vetor[2]);

Vetor posicao 0: 8
Vetor posicao 2: 67


In [9]:
# Alterando vetores
vetor[1] = 231
vetor[3] = 105
print(vetor)

[  8 231  67 105]


## Criação de vetores

Podemos também criar vetores vazios, com valores igual a zero, com valores igual a 1, com valores uniformemente distribuídos ou com valores aleatórios (dentro de intervalos que podemos pré-determinar). Para isso temos as seguintes funções:
 
empty (quantidade_de_elementos, tipo_de_dados): criar matriz com valores vazios.

zeros (quantidade_de_elementos, tipo_de_dados): criar matriz com valores igual a zero.

ones(quantidade_de_elementos, tipo_de_dados): criar matriz com valores igual a 1.

arange(valor_inicial, valor_de_parada ,passo ,tipo_de_dados): criar matriz com valores uniformemente distribuídos

random.random(quantidade_de_elementos): gerar número randômico, ponto flutuante, entre 0 e 1.

* valor inicial: valor de início do intervalo. O valor padrão é 0.
* valor de parada: enquanto for menor que este valor os valores são incluiídos na matriz.
* Passo: o espaçamento entre os valores. O valor padrão é 1.
* tipo_de_dados: o tipo de saída dos dados. Se não for especificado, o tipo de dados será o mesmo que o do valor inicial

Nota: o campo tipo_de_dados é opcional, ou seja, não sou obrigado a informar.

In [15]:
# Exemplo
vetor01 = np.empty(10,int)
print(vetor01)

vetor02 = np.zeros(10)
print(vetor02)

vetor03 = np.ones(10)
print(vetor03)

vetor04 = np.arange(3,13,2,float);
print(vetor04)

vetor05 = 6*np.random.random(5);
print(vetor05)

[4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 3.  5.  7.  9. 11.]
[0.25978901 5.72175613 1.04572401 2.01203271 0.51408208]
